name: Create Release

on:
  push:
    branches: [ "main" ]

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_outputs.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Resolve Version
        id: resolve-version
        run: |
          echo "::set-output name=version::1000"
          echo "resolved version: ${{ steps.resolve-version.outputs.version }}"
      - name: Create Branch
        run: |
          git switch -c release-${{ steps.set_outputs.outputs.version }}
          git push -u origin release-${{ steps.set_outputs.outputs.version }}

  perform-release:
    name: Perform Release
    needs: prepare-release
    uses: ./.github/workflows/perform-release.yml
    with:
      version: ${{ needs.prepare-release.outputs.version }}
    secrets: inherit

  update-docs:
    name: Update Documentation
    needs: perform-release
    uses: ./.github/workflows/update-documentation.yml
            
