name: Create Release

on:
  push:
    branches: [ "main" ]

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.resolve-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Resolve Version
        id: resolve-version
        run: |
          version=$(mvn help:evaluate -Dexpression='project.version' -q -DforceStdout)
          if [[ "$version" =~ /^[0-9]+(\.[0-9]+)*-SNAPSHOT$ ]];
          then
            echo "matching"
          else
            echo "not matching"
          fi
          export VERSION=${version:0:${#version} - 9}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Create Branch
        run: |
          git switch -c release-${{ steps.resolve-version.outputs.version }}
          git push -u origin release-${{ steps.resolve-version.outputs.version }}

  perform-release:
    name: Perform Release
    needs: prepare-release
    uses: ./.github/workflows/perform-release.yml
    with:
      version: ${{ needs.prepare-release.outputs.version }}
    secrets: inherit

  update-docs:
    name: Update Documentation
    needs: perform-release
    uses: ./.github/workflows/update-documentation.yml
            
