name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (eg: 1.0.0)'
        required: true
        type: string
      next-version:
        description: 'Next version (eg: 1.0.1-SNAPSHOT)'
        required: false
        type: string

jobs:

  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Branch
        run: |
          git switch -c release-${{ inputs.version }}
          git push -u origin release-${{ inputs.version }}
          git switch main

  perform-release:
    name: Perform Release
    needs: prepare-release
    uses: ./.github/workflows/perform-release.yml
    with:
      version: ${{ inputs.version }}
      next-version: ${{ inputs.next-version }}
    secrets: inherit

  update-docs:
    name: Update Documentation
    needs: perform-release
    uses: ./.github/workflows/update-documentation.yml
            
