name: Perform Tag

on:
  workflow_call:
    inputs:
      version:
        description: 'Tag version (eg: 1.0.0)'
        required: true
        type: string
      next-version:
        description: 'Next version (eg: 1.0.1-SNAPSHOT)'
        required: false
        type: string

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: tag-${{ inputs.version }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Configure Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Maven Release Prepare
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B release:prepare -DreleaseVersion='${{ inputs.version }}' \
          -DdevelopmentVersion='${{ inputs.next-version }}'